name: shopapp_tuto
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.4.1
  shared_preferences: ^0.5.6+3
  fluttertoast: ^4.0.1
  firebase_database: ^3.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - Images/Icons/back1.png
  - Images/Icons/back2.png
  - Images/Icons/blazer1.png
  - Images/Icons/sneaker.png
  - Images/Icons/chemise1.png
  - Images/Icons/chemise2.png
  - Images/Icons/boxers1.png
  - Images/Icons/boxers2.png
  - Images/Icons/jacket1.png
  - Images/Icons/jacket2.png
  - Images/Icons/patalon1.png
  - Images/Icons/pantalon2.png
  - Images/Icons/robe1.png
  - Images/Icons/robe2.png
  - Images/Icons/tshirst.png
  - Images/Icons/tshirt1.png
  - Images/Icons/tshirt2.png
  - Images/Icons/vans1.png
  - Images/Icons/vans2.png
  - Images/Icons/veston1.png
  - Images/Icons/veston2.png
  - Images/Icons/bote.png
  - Images/Produit/airmax.jpg
  - Images/Produit/blaser.jpg
  - Images/Produit/blaser1.jpg
  - Images/Produit/chemise.jpg
  - Images/Produit/chemise1.jpg
  - Images/Produit/chemise2.jpg
  - Images/Produit/cuire.jpg
  - Images/Produit/jeans.jpg
  - Images/Produit/jeans1.jpg
  - Images/Produit/pull.jpg
  - Images/Produit/robes.jpg
  - Images/Produit/robes1.webp
  - Images/Produit/robes2.jpg
  - Images/Produit/sac.jpg
  - Images/Produit/sac1.jpg
  - Images/Produit/sac2.jpg
  - Images/Produit/sac3.jpg
  - Images/Produit/sac4.jpg
  - Images/Produit/sneaker.jpg
  - Images/Produit/sneaker1.jpg
  - Images/Produit/tshirt.png
  - Images/Produit/tshirt1.jpg
  - Images/Produit/tshirt2.jpg
  - Images/Produit/veste.jpg
  - Images/Produit/veste1.jpg
  - Images/Produit/veste2.jpg
  - Images/background/man.jpg
  - Images/background/back.jpg
  - Images/background/woman.jpg
  - Images/background/logo.png
  - Images/background/logo1.png
  - Images/background/logo2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
